/* Generated By:JJTree: Do not edit this line. ASTAnd.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package textdb.parser;

public
class ASTAnd extends SimpleNode {
  public ASTAnd(int id) {
    super(id);
  }

  public ASTAnd(SimpleParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e0e38c69bd79e4cf21a8d0aff1b87ce9 (do not edit this line) */
