/* Generated By:JJTree: Do not edit this line. ASTAop.java */
package textdb.parser;

public class ASTAop extends SimpleNode {
  public ASTAop(int id) {
    super(id);
  }

  public ASTAop(SimpleParser p, int id) {
    super(p, id);
  }

  public void setName(String n) {
    name = n;
  }

  public String toString() {
    return "Arith_Op: "+name;
  }

  private String name;

}
