/* Generated By:JJTree: Do not edit this line. ASTASC.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package textdb.parser;

public
class ASTASC extends SimpleNode {
  public ASTASC(int id) {
    super(id);
  }

  public ASTASC(SimpleParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=51d69c9de69bc2134f938e40ee9c9632 (do not edit this line) */
