/* Generated By:JJTree: Do not edit this line. ASTAdd.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package textdb.parser;

public
class ASTAdd extends SimpleNode {
  public ASTAdd(int id) {
    super(id);
  }

  public ASTAdd(SimpleParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f989ab19a6738bdec3d5c426c268fc0e (do not edit this line) */
