/* Generated By:JJTree: Do not edit this line. ASTCop.java */
package textdb.parser;

public class ASTCop extends SimpleNode {
  public ASTCop(int id) {
    super(id);
  }

  public ASTCop(SimpleParser p, int id) {
    super(p, id);
  }
  public void setName(String n) {
    name = n;
  }

  public String toString() {
    return "Comparison_Op: "+name;
  }

  private String name;


 public String getName() {
    return name;
  }
}