/* Generated By:JJTree: Do not edit this line. ASTDESC.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package textdb.parser;

public
class ASTDESC extends SimpleNode {
  public ASTDESC(int id) {
    super(id);
  }

  public ASTDESC(SimpleParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=425bcd2aed7c52076d7c9088b8562551 (do not edit this line) */
