/* Generated By:JJTree: Do not edit this line. ASTFrom.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package textdb.parser;

public
class ASTFrom extends SimpleNode {
  public ASTFrom(int id) {
    super(id);
  }

  public ASTFrom(SimpleParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f64789f66de304fc4df479c47cb79990 (do not edit this line) */
