/* Generated By:JJTree: Do not edit this line. ASTJoinExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package textdb.parser;

public
class ASTJoinExpr extends SimpleNode {
  public ASTJoinExpr(int id) {
    super(id);
  }

  public ASTJoinExpr(SimpleParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=550a0c65d618fb6ce7c6fe8811ba629e (do not edit this line) */
