/* Generated By:JJTree: Do not edit this line. ASTOrderby.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package textdb.parser;

public
class ASTOrderby extends SimpleNode {
  public ASTOrderby(int id) {
    super(id);
  }

  public ASTOrderby(SimpleParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3fd03849d4f0c860358041222f5cb357 (do not edit this line) */
