/* Generated By:JJTree: Do not edit this line. ASTOrderBy.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package textdb.parser;

public
class ASTOrderBy extends SimpleNode {
  public ASTOrderBy(int id) {
    super(id);
  }

  public ASTOrderBy(SimpleParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d287cffd80190bcdd8021cdfa0fe3d0a (do not edit this line) */
