/* Generated By:JJTree: Do not edit this line. ASTOn.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package textdb.parser;

public
class ASTOn extends SimpleNode {
  public ASTOn(int id) {
    super(id);
  }

  public ASTOn(SimpleParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=aafe92b6a563c5eddcd02f83d2064bec (do not edit this line) */
