/* Generated By:JJTree: Do not edit this line. ASTOrderExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package textdb.parser;

public
class ASTOrderExpr extends SimpleNode {
  public ASTOrderExpr(int id) {
    super(id);
  }

  public ASTOrderExpr(SimpleParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bd621151a9d6fb4016c70fb7815fa456 (do not edit this line) */
