/* Generated By:JJTree: Do not edit this line. ASTString.java */
package textdb.parser;

public class ASTString extends SimpleNode {
  public ASTString(int id) {
    super(id);
  }

  public ASTString(SimpleParser p, int id) {
    super(p, id);
  }

  public void setName(String n) {
    name = n;
  }

  public String toString() {
    return "String: "+name;
  }

  private String name;

}
