/* Generated By:JJTree: Do not edit this line. ASTSelect.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package textdb.parser;

public
class ASTSelect extends SimpleNode {
  public ASTSelect(int id) {
    super(id);
  }

  public ASTSelect(SimpleParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d68414627737ec22fc9bc51f5b61b862 (do not edit this line) */
