/* Generated By:JJTree: Do not edit this line. ASTWhere.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package textdb.parser;

public
class ASTWhere extends SimpleNode {
  public ASTWhere(int id) {
    super(id);
  }

  public ASTWhere(SimpleParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5fcb143732ff713da89a5590c3b793d0 (do not edit this line) */
