/* Generated By:JavaCC: Do not edit this line. parserTreeConstants.java Version 5.0 */
package textdb.parser;

public interface parserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTSELECT = 2;
  public int JJTFROM = 3;
  public int JJTJOINEXPR = 4;
  public int JJTON = 5;
  public int JJTWHERE = 6;
  public int JJTADD = 7;
  public int JJTAOP = 8;
  public int JJTMOP = 9;
  public int JJTMULT = 10;
  public int JJTUNARY = 11;
  public int JJTOR = 12;
  public int JJTAND = 13;
  public int JJTNOT = 14;
  public int JJTCOP = 15;
  public int JJTINTEGER = 16;
  public int JJTREAL = 17;
  public int JJTSTRING = 18;
  public int JJTMYID = 19;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Select",
    "From",
    "JoinExpr",
    "On",
    "Where",
    "Add",
    "Aop",
    "Mop",
    "Mult",
    "Unary",
    "Or",
    "And",
    "Not",
    "Cop",
    "Integer",
    "Real",
    "String",
    "MyID",
  };
}
/* JavaCC - OriginalChecksum=e0eb98f1fc4231395afc11698f90b3bf (do not edit this line) */
