/* Generated By:JavaCC: Do not edit this line. SimpleParserTreeConstants.java Version 7.0.10 */
package textdb.parser;

public interface SimpleParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTSELECT = 2;
  public int JJTFROM = 3;
  public int JJTJOINEXPR = 4;
  public int JJTON = 5;
  public int JJTWHERE = 6;
  public int JJTADD = 7;
  public int JJTAOP = 8;
  public int JJTMOP = 9;
  public int JJTMULT = 10;
  public int JJTOR = 11;
  public int JJTAND = 12;
  public int JJTNOT = 13;
  public int JJTCOP = 14;
  public int JJTINTEGER = 15;
  public int JJTREAL = 16;
  public int JJTSTRING = 17;
  public int JJTMYID = 18;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Select",
    "From",
    "JoinExpr",
    "On",
    "Where",
    "Add",
    "Aop",
    "Mop",
    "Mult",
    "Or",
    "And",
    "Not",
    "Cop",
    "Integer",
    "Real",
    "String",
    "MyID",
  };
}
/* JavaCC - OriginalChecksum=fdd0f8fb42852959bd7e1df2a00a5642 (do not edit this line) */
