/* Generated By:JavaCC: Do not edit this line. SimpleParserTreeConstants.java Version 7.0.10 */
package textdb.parser;

public interface SimpleParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTSELECT = 2;
  public int JJTFROM = 3;
  public int JJTJOINEXPR = 4;
  public int JJTON = 5;
  public int JJTWHERE = 6;
  public int JJTORDERBY = 7;
  public int JJTORDEREXPR = 8;
  public int JJTASC = 9;
  public int JJTADD = 10;
  public int JJTAOP = 11;
  public int JJTMOP = 12;
  public int JJTMULT = 13;
  public int JJTOR = 14;
  public int JJTAND = 15;
  public int JJTNOT = 16;
  public int JJTCOP = 17;
  public int JJTINTEGER = 18;
  public int JJTREAL = 19;
  public int JJTSTRING = 20;
  public int JJTMYID = 21;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Select",
    "From",
    "JoinExpr",
    "On",
    "Where",
    "OrderBy",
    "OrderExpr",
    "ASC",
    "Add",
    "Aop",
    "Mop",
    "Mult",
    "Or",
    "And",
    "Not",
    "Cop",
    "Integer",
    "Real",
    "String",
    "MyID",
  };
}
/* JavaCC - OriginalChecksum=b57603e593a956c64c36f77c30a8d40f (do not edit this line) */
